library(ggsci)
library(ggplot2)
colorsQ = c(pal_nejm("default")(5),"grey50","grey30")
data <- read.table("S_F15.table.txt",head=T)
data$round <- factor(data$round, levels = c("First", "Second","Third"), labels = c("De novo Assemble", "First Filter","Second Filter"))
data$specy <- factor(data$specy, levels = c("COVID","IVA"), labels = c("SARS-2-Cov","IVA"))
cR = rev(pal_nejm("default")(3))
MainAB <- read.table("S_F15.table.A_B.txt",head=T)
MainAB$IVA_reads_L = log(MainAB$IVA_reads)
p1 = ggboxplot(data, x = "round", y = "coverage", color = "specy",add = "jitter", palette = "nejm") + facet_wrap(~ specy) +     theme(legend.position = "none",axis.text.x = element_text(size = 8)) +    labs(x = "", y = "Genomic Coverage") +  ggtitle("B")
p2 = ggboxplot(data, x = "round", y = "signalRatio", color = "specy",add = "jitter", palette = "nejm") + facet_wrap(~ specy) +  theme(legend.position = "none",axis.text.x = element_text(size = 8)) +labs(x = "", y = "Signal Ratio") +ggtitle("C")
